version: '3.8'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '5173:5173'
    volumes:
      - .:/code
      - /code/node_modules
    environment:
      - NODE_ENV=development
    container_name: nolatech-frontend-admin
    command: pnpm run dev --host 0.0.0.0 --port 5173
    networks:
      - app-network

  prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    container_name: nolatech-frontend-admin
    command: node build
    networks:
      - app-network

networks:
  app-network:
